spring:
  application:
    name: aaron-ai-agent
  profiles:
    active: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:your-api-key-here}
      chat:
        options:
          model: qwen-turbo-2025-04-28

    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aaron.aaronaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
app:
  security:
    jwt:
      secret: VGhpc0lzQUNvZGV4RGVtb1NlY3JldEtleUZvckpXVFRva2VuQXV0aA==
      expire-seconds: 7200
