create table if not exists rbac_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    nickname varchar(64) not null,
    password_hash varchar(255) not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists rbac_role (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name varchar(64) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists rbac_permission (
    id bigint generated by default as identity primary key,
    code varchar(128) not null unique,
    name varchar(128) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists rbac_user_role (
    user_id bigint not null references rbac_user(id) on delete cascade,
    role_id bigint not null references rbac_role(id) on delete cascade,
    primary key (user_id, role_id)
);

create table if not exists rbac_role_permission (
    role_id bigint not null references rbac_role(id) on delete cascade,
    permission_id bigint not null references rbac_permission(id) on delete cascade,
    primary key (role_id, permission_id)
);

create table if not exists rbac_menu (
    id bigint generated by default as identity primary key,
    parent_id bigint references rbac_menu(id) on delete cascade,
    name varchar(64) not null,
    path varchar(128) not null unique,
    permission_id bigint not null references rbac_permission(id) on delete cascade,
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp
);
